    $(function(){
        $(".page4_content").mouseover(function(){
            $(".page4_bg_opacity").show()
            $(this).stop().css({width:"36%"}).siblings().css({width:"16%"})
            $(this).mouseleave(function(){
                $(this).css({width:""}).siblings().css({width:""})
            })
        })

        $(".page4_con1").mouseenter(function(){
            $(".page4_bg_img").css({background:"url(img/check2.jpg)","background-size":"cover","background-position":"center"})
            $(this).find(".page4_con_info").fadeIn()
        })
        $(".page4_con2").mouseenter(function(){
            $(".page4_bg_img").css({background:"url(img/acting.jpg)","background-size":"cover","background-position":"center"})
            $(this).find(".page4_con_info").fadeIn()
        })
        $(".page4_con3").mouseenter(function(){
            $(".page4_bg_img").css({background:"url(img/durability2.jpg)","background-size":"cover","background-position":"center"})
            $(this).find(".page4_con_info").fadeIn()
        })
        $(".page4_con4").mouseenter(function(){
            $(".page4_bg_img").css({background:"url(img/teamwork2.jpg)","background-size":"cover","background-position":"center"})
            $(this).find(".page4_con_info").fadeIn()
        })
        $(".page4_con5").mouseenter(function(){
            $(".page4_bg_img").css({background:"url(img/influence.jpg)","background-size":"cover","background-position":"center"})
            $(this).find(".page4_con_info").fadeIn()
        })

        $(".page4_contents").mouseenter(function(){
            $(".page4").css({color:"#fff"})
            $(".page4_con_txt>span").css({color:"#fff"})
            $(".page4_con_txt").css({color:"#fff"})
            $(".page4_content").css({"border-color":"#fff"})
            $(".page4_contents").css({"border-color":"#fff"})
        })
        $(".page4_content").mouseleave(function(){
            $(".page4_con_info").hide()
        })

        $(".page4_contents").mouseleave(function(){
            $(".page4_con_txt>span").css({color:""})
            $(".page4_bg_opacity").hide()
            $(".page4_bg_img").css({background:""})
            $(".page4").css({color:"#333"})
            $(".page4_con_txt").css({color:"#333"})
            $(".page4_content").css({"border-color":""})
            $(".page4_contents").css({"border-color":""})
        })
    })